spring.application.name=food-saver

server.port=8040

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/food_saver_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

foodsaver.surplus-detection.threshold-quantity=${SURPLUS_DETECTION_THRESHOLD:5.000}
foodsaver.food-eligibility.policy.effective-from=${FOOD_ELIGIBILITY_POLICY_EFFECTIVE_FROM}
foodsaver.ordering.reservation-ttl=${RESERVATION_TTL:PT15M}