package com.foodsaver.enums;

public enum FoodEligibilityReasonCode {
	SURPLUS_DETECTION_NOT_ELIGIBLE,
	REQUIRED_FACT_MISSING,
	FACT_CONFLICT,
	POLICY_NOT_APPLICABLE,
	POLICY_AMBIGUOUS,
	POLICY_RULE_BLOCKED,
	OWNERSHIP_MISMATCH
}
